### ISSUE TITLE
v5s的预训练权重

### ISSUE THREAD

**Issue by zhmcnmb** [QY1994-0919/CFPNet#11]
你好，作者，请问可以提供在v5网络上的预训练权重吗？

**Comment by dongzhang89** [comment]
@zhmcnmb 你好，近期我们正在对CFP的代码进行整理，所有的权重随后会一起发布，感谢关注！

**Comment by yjq404** [comment]
你好，请问整理后的代码什么时候能发？感谢

**Comment by dongzhang89** [comment]
@yjq404 @zhmcnmb  已加！

**Comment by yjq404** [comment]
@dongzhang89 你好，六个权重下载的时候网盘都显示“文件被所有者删除，操作失败”

**Comment by yjq404** [comment]
@dongzhang89 找到了，感谢感谢

**Comment by zhmcnmb** [comment]
> @yjq404@zhmcnmb 已加！
谢谢，请问v5权重里面有个CCFormer模块和ECVMBlock模块是不是yolox里面的ECVBlock，只是命名不同

**Comment by QY1994-0919** [comment]
是的
















在 2023-03-14 23:40:50，"zhmcnmb" ***@***.***> 写道：

@***@***.*** 已加！
谢谢，请问v5权重里面有个CCFormer模块和ECVMBlock模块是不是yolox里面的ECVBlock，只是命名不同

**Comment by zhmcnmb** [comment]
> 是的 在 2023-03-14 23:40:50，"zhmcnmb" ***@***.***> 写道： @***@***.*** 已加！ 谢谢，请问v5权重里面有个CCFormer模块和ECVMBlock模块是不是yolox里面的ECVBlock，只是命名不同 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by zhmcnmb** [comment]
> 是的 在 2023-03-14 23:40:50，"zhmcnmb" ***@***.***> 写道： @***@***.*** 已加！ 谢谢，请问v5权重里面有个CCFormer模块和ECVMBlock模块是不是yolox里面的ECVBlock，只是命名不同 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
v5权重无法全部引用，可以看一下v5model文件夹里面的common.py文件吗
