### ISSUE TITLE
显存爆炸，Evc显存占用太大

### ISSUE THREAD

**Issue by Bian-666** [QY1994-0919/CFPNet#17]
您好，感谢你们优秀的工作，看了论文结果感觉挺不错的。
        但是我加到我改的yolov5中训练直接爆显存了（加之前只占用14G，加完直接爆显存，Rtx3090），除了降低bs和降低输入图片分辨率，有什么办法可以降低显存占用吗？

**Comment by dongzhang89** [comment]
@Bian-666 请问你是加在哪个位置的，可以把实施细节介绍一下吗？@QY1994-0919 我们的好像没有出现过这个问题？你回答一下这个提问

**Comment by Bian-666** [comment]
> @Bian-666 请问你是加在哪个位置的，可以把实施细节介绍一下吗？@QY1994-0919 我们的好像没有出现过这个问题？你回答一下这个提问

我尝试过加在第4层后面【256，256】，还有试过加在第11层unsample【512，512】后面，使用的是yolov5l，都爆显存

**Comment by QY1994-0919** [comment]
@Bian-666  可以参考 #10

**Comment by Bian-666** [comment]
> @Bian-666 可以参考 #10

谢谢回复，我添加EVC模块并没有遇到问题，问题是EVC模块显存的占用太大了，貌似超过了10个G？

**Comment by dongzhang89** [comment]
@Bian-666 不会占那么大显存的，你发邮件给quanyu，让她帮你具体看一下是什么原因

**Comment by tongyang-218** [comment]
我也是相同的问题，显存占用特别多，具体的解决方法是什么呢

**Comment by 1nancy23** [comment]
> 您好，感谢你们优秀的工作，看了论文结果感觉挺不错的。 但是我加到我改的yolov5中训练直接爆显存了（加之前只占用14G，加完直接爆显存，Rtx3090），除了降低bs和降低输入图片分辨率，有什么办法可以降低显存占用吗？

这个EVC中间过程量估计很大
