### ISSUE TITLE
EVC 是否支持其他模型？

### ISSUE THREAD

**Issue by okt7760** [QY1994-0919/CFPNet#20]
我看大部分都是使用在 yolo 上，请问该模块是否适用与其他网络上？

**Comment by dongzhang89** [comment]
@okt7760 当然可以。
EVC 作为一种除了attention之外的可以用来捕捉图像关注重点的方法，不仅可以适用于其他的网络上，而且还可以适用于其他的任务，比如segmentation。如果你有在其他模型或者任务上的实验结果，欢迎report或提交[Pull requests]。
感谢关注。
